### ISSUE TITLE
Add option for visitor to become a host of a new chain

### ISSUE THREAD

**Issue by navase** [pim0223/clothing-chain-frontend#21]
If there is no chain in the users area, the user can start a new chain and becomes a host.

- Decide where to put this option on the website.
- The user gets a user account on the website.
- The user can start a new chain. (Options: in the same form as the user account creation, or as a separate form when logged in).

**Comment by pim0223** [comment]
Duplicate of https://github.com/pim0223/clothing-chain-frontend/issues/4; only the user accoung locig needs to be figured out.
