### ISSUE TITLE
Add address picker and first and last name to signup form

### ISSUE THREAD

**Issue by navase** [pim0223/clothing-chain-frontend#46]
These turned out to be necessary or really useful (e.g. people with the same first name, or same street in different village.)

**Comment by pim0223** [comment]
We use an address API, so no need for postal code, city. You just start typing your address and select it. @giuliamml does this work as expected? If not sure, let's take some time this week to check what we need to still do here.

**Comment by giuliamml** [comment]
@pim0223 used Geocoding to implement this feature. Can get a list of addresses but don't think this API is as accurate in terms of retrieving specific full addresses: 

https://user-images.githubusercontent.com/52887737/114882858-4a5f2180-9dfc-11eb-9637-071d16e02e58.mov

There's a [Google Maps Library ](https://www.npmjs.com/package//react-places-autocomplete) which might be of better use for this functionality. Going to give it a try, what do you think?

**Comment by pim0223** [comment]
Yeah that looks good, haven't tried it myself. Let me know if you can get it to work!
